FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update

RUN apt-get install -y --no-install-recommends \
	build-essential binutils-dev libncurses5-dev libssl-dev ccache bison flex libelf-dev
